services:
  postgres:
    image: postgres:18
    container_name: recipe-app-postgres
    environment:
      POSTGRES_USER: recipe_app
      POSTGRES_PASSWORD: recipe_app_password
      POSTGRES_DB: recipe_app
    ports:
      - "5432:5432"
    volumes:
      - recipe-app-postgres-data:/var/lib/postgresql

  app:
    build: .
    container_name: recipe-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipe_app
      SPRING_DATASOURCE_USERNAME: recipe_app
      SPRING_DATASOURCE_PASSWORD: recipe_app_password

volumes:
  recipe-app-postgres-data: