# suppress inspection "UnusedProperty" for whole file
spring.application.name=recipe-app

spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_app
spring.datasource.username=recipe_app
spring.datasource.password=recipe_app_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true